site_name: Lekvalvet
site_url: https://mydomain.org/mysite
copyright: Lekbanken is marked with CC0 1.0 Universal
plugins:
  - meta
  - tags
theme:
  name: material
  language: sv
  icon:
    logo: fontawesome/solid/people-group
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Byt till mörkt läge

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Byt till ljust läge
extra:
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/Bjorkan/Lekvalvet