site_name: Lekvalvet
site_url: https://mydomain.org/mysite
copyright: Lekbanken is marked with CC0 1.0 Universal
plugins:
  - meta
  - tags
theme:
  name: material
  language: sv
  icon:
    logo: fontawesome/solid/people-group
extra:
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/Bjorkan/Lekvalvet