name: Försöker bygga hemsidan
on:
  pull_request:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Hämta Pull Request
        uses: actions/checkout@v4
      - name: Förbered Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Ladda ner Material for MkDocs
        run: pip install mkdocs-material 
      - name: Bygg hemsidan
        run: mkdocs build
      - name: Ladda upp den byggda hemsidan
        uses: actions/upload-artifact@v4
        with:
          name: Hemsidan
          path: site/
          if-no-files-found: error
